export * from './database.types'
export * as personalDataType from './personalData/personalDataType'
export * as servicesType from './services/servicesType'
export * as skillsType from './skills/skillsType'
export * as projectsType from './projects/projectsType'